### PR TITLE
sanic-openapi 0.5.0; many fixes, see description

### PR DESCRIPTION
**Pull request by DirkGuijt**
- updated the swagger UI to version v3.9.2
- added decorator to provide reponse documentation for non-200 status codes
- now possible to configure security/authorization for swagger
- now possible to set the host and basepath parameters
- fixed the issue where swagger always expects the openapi/spec.json path to be at the root of the url path
- added doc field-type specifically for post endpoints that consumes a json body (the openapi spec is invalid when using a standard dictionary for this)
- removed the openapi blueprint and put everything under the swagger blueprint
- fixed some other openapi spec invalidities
- updated requirements
- bumped minor version for sanic-openapi to 0.5.0
- updated the README.md file

### CODE REVIEW

**Comment by arnulfojr** [comment]
@channelcat is there any reason why this PR hasn't been merged?

**Comment by arnulfojr** [comment]
I personally like the fact that you can include openapi blueprint without requiring swagger's blueprint, give more flexibility

**Comment by TheGrandmother** [comment]
Yes please merge this.
Decent open-api support is vital for me.

**Comment by TheGrandmother** [comment]
@Typhon66 Could you take a look?

**Comment by mt-rahul** [comment]
Has it been merged? I don't see these fixes and master branch.

**Comment by TheGrandmother** [comment]
Hi!
No there haven't been any updates on this.

I suggest that you use marshmallows [apispec](https://github.com/huge-success/sanic-openapi). I may get around to writing a sanic plugin for it, but I have been using it as a standalone library.

**Comment by DirkGuijt** [comment]
The update is that, recently, the community took back control of the main sanic project because the original owner vanished. Sanic-openapi was part of that control and now that this have been going better for the Sanic main project, the openapi extension will also get more traction (hopefully).

See also the community forums at https://community.sanicframework.org/t/about-the-package-sanic-openapi-category/42/2

**Comment by mt-rahul** [comment]
@DirkGuijt I see. I hope to see this PR merged asap.

**Comment by DirkGuijt** [comment]
@mt-rahul me too... it's my life long dream (of the past year)

**Comment by hampsterx** [comment]
It's also my dream to get this merged, there will be a party in the street~ 

 I notice I end up with double routes. Not sure if it's just this branch, having trouble with master. I end up with

```
/my-route/{id}: {
...
/my-route/{id}/: {
```
for every route?

**Comment by TheGrandmother** [comment]
@itielshwartz
You just write your OpenApi style docstrings and then somewhere do a `spec.add_path(self.prefix + '/', func=get_func)` where `spec` is the `APISpec` object and `get_func` is just the handler function.

**Comment by vaulstein** [comment]
Is this pull requests going to be merged?

**Comment by DirkGuijt** [comment]
I posted a message on the sanic community forum again. The main Sanic project was just released so hopefully there is now some time to look at this...

**Comment by ahopkins** [comment]
@DirkGuijt Can you update from master, fix the conflict and push a new commit?

**Comment by DirkGuijt** [comment]
> @DirkGuijt Can you update from master, fix the conflict and push a new commit?

I'll see if I can do that tomorrow!

**Comment by DirkGuijt** [comment]
I'll accept your approvals now... ;)

**Pull request merged**
