### PR TITLE
Fixes #103 and the git history mess up of #104

### LINKED ISSUE #103: Make it possible to register the same model definition multiple times in `doc.definitions`
Hi,

We plan to document our API with `sanic-openapi`, I'm currently implementing some tooling for it. We tried to reuse some consumed/produced model definitions in the doc of multiple API endpoints, but it turns out reusing the same class wrapped in different `doc.Object` instances is not supported by the framework, even if `object_name` is different in every case.

Would it be possible to register `Object` instances in `definitions` with `self.object_name` instead of `self.cls`? I've tested it locally and it seems to work.

Here is my workaround code:

```Python
class Object(doc.Object):

    def __init__(self, cls, *args, object_name=None, **kwargs):
        super().__init__(cls, *args, object_name=object_name, **kwargs)
        
        doc.definitions[self.object_name] = doc.definitions[self.cls]
        del doc.definitions[self.cls]
```

PS.: Thanks for your efforts!

### PR DESCRIPTION
**Pull request by volfpeter**
Please close PR #104 and merge this instead (fixed git history and merge conflicts).

### CODE REVIEW

**Comment by volfpeter** [comment]
Black would like to reformat most of `swagger.py`...

**Comment by chenjr0719** [comment]
Yep, but I think it is necessary to keep the same coding style not only in this project but also under organization umbrella. And about `black`, I've to say it is a nice formatting tool which only needs minimal effort to use it. Give it some time, I think you will like it.

**Comment by ahopkins** [comment]
I think it is really quite incredible at how fast it has become adopted by the community. Have you noticed lately that the repo has recently be moved?

https://github.com/python/black

**Comment by volfpeter** [comment]
@ahopkins What is the status of this PR? Do i need to do anything before it can be merged?

**Comment by ahopkins** [comment]
@volfpeter Thanks. I missed the approval.

**Pull request merged**
