### PR TITLE
add support for HTTPMethodView

### PR DESCRIPTION
**Pull request by morentharia**
```python
from sanic.views import HTTPMethodView
from sanic.response import json

class CarHandler(HTTPMethodView):
    @doc.summary("Get a car")
    async def get(self, request):
        return json(dict(get='get'))

    @doc.summary("Post a car")
    async def post(self, request):
        return json(dict(post='post'))
```

### CODE REVIEW

**Comment by wswld** [comment]
This would indeed be very useful.

**Comment by sebjamesfd** [comment]
@morentharia Nice work!

Unfortunately this will not add the blueprint tags to each method resulting in swagger showing the methods as belonging to the "default" blueprint.

Some similar work of retrieving the route_specs of each method and assigning the blueprint name as tags here https://github.com/channelcat/sanic-openapi/blob/master/sanic_openapi/openapi.py#L50

**Comment by logileifs** [comment]
Can we get this pull request or [64](https://github.com/huge-success/sanic-openapi/pull/64) merged?
Is there something I can do to help? I could resolve the conflicts if that's the only thing keeping this from being merged

**Comment by chenjr0719** [comment]
Thanks for contribution but I'm going to close this PR because it is duplicated with #64.

**Pull request closed without merging**
