### PR TITLE
Release 0.6.2

### PR DESCRIPTION
**Pull request by chenjr0719**
Hi @ahopkins, May I ask your help to release new version of `sanic-openapi`? This release will fix the `not JSON serializable` issue caused by `usjon>=2`.

### CODE REVIEW

**Comment by ahopkins** [comment]
Will take a look later tonight 💪

**Comment by ioggstream** [comment]
news on that?

**Comment by wei-hai** [comment]
+1

**Comment by srkama** [comment]
@chenjr0719 when are we planning to release? The current master is not compatible with Sanic.

**Comment by ahopkins** [comment]
0.6.2 released. I did not prepare release notes, if someone can I will be happy to include them.

**Pull request merged**
