### PR TITLE
Added an api module, implements #107

### PR DESCRIPTION
**Pull request by volfpeter**
Added an `api` module, that contains:
- `API`: The base class to extend to document routes using a class-based syntax and possibly a single decorator. See its documentation for a proper description and example usage.
- `Response`: Helper class that is required by `API` to support `doc.response()`.

### CODE REVIEW

**Comment by chenjr0719** [comment]
@volfpeter I will review this PR after #109 is done if you don't mind. I want to make standard test cases for this project first.
Before that, is it possible to add tests for this PR? I feel a little unsafe to put this into project without tests.

**Comment by volfpeter** [comment]
Sure, it's a good idea. I'll have a look at the current test cases to see how I can write some for this module.
Also, if you have any questions regarding the api module, please let me know. I know it's a quite large addition to the project and it requires a thorough review.

**Comment by volfpeter** [comment]
I've added tests for the `api` module (160+ lines, much more than all other tests combined).
- `test_message_api_response()` basically checks the `decorators` class attribute's implementation.
- `test_documentation()` compares the resulting `swagger.json` to a benchmark `swagger.json` (tests create an app with `api`-based docs and a benchmark app with `doc`-based docs).

`api` code coverage is 70% right now. Here is a list of things that are not tested yet:
- The `exclude` class attribute.
- Routing methods except `post()`.
- Inline overrides in the decorator (like `MessageAPI(consumes_content_type="application/xml", tag="xml") \ def foo(request): ...`).

**Comment by ahopkins** [comment]
@volfpeter Can you run `git rebase -i` (or some other method) to squash your commits into a single?

**Comment by volfpeter** [comment]
For the record, since my previous comment, I've added tests for:
- The `exclude` class attribute.
- All routing methods.
- Inline override for the `exclude` class attribute.

Code coverage is over 90% after these changes, but of course there are plenty of things that could still be tested.

**Comment by volfpeter** [comment]
@chenjr0719 What is the status of this PR? Do you have an estimate when it could get a review?

**Comment by volfpeter** [comment]
@chenjr0719 Hi! Could you please give an estimate when this PR might get reviewed?

**Comment by chenjr0719** [comment]
@volfpeter Sorry about no response. I think I can get this done at the end of this Friday. Little busy recent days.

**Comment by volfpeter** [comment]
Thanks. No problem! I just wanted to get some feedback on how things are going.

**Comment by volfpeter** [comment]
@chenjr0719 I've marked the test as skipped.

Thanks for the review and for accepting a whole new module into your project! I'm really happy to have contributed here.

One thing I miss a bit is a readme update. Should i do it? I didn't want to start editing the readme without permission or guidance on where you would like to have info about the `api` module...

**Comment by chenjr0719** [comment]
@volfpeter Actually, I would like to create a new document of this project with `mkdocs` and hosted on readthedocs. This will not only include how-to document but also include all API reference with your awesome works. But this might not be ready in recent days(at least after two weekends). So, I suggest that you can put the document at `README` or somewhere(e.g., `docs/api_module.md`) if you feel comfortable.

**Comment by volfpeter** [comment]
That's great! In this case, I'll leave everthing as it is right now, but please let me know if you need help writing documentation for this module. I'd be happy to help.

**Pull request merged**
