### PR TITLE
Add basic support for type hinting-based docs

### PR DESCRIPTION
**Pull request by viniciusd**
Incrementally addresses #128

A working example that fully works after these changes:
```python
from sanic import Sanic
from sanic_openapi import doc, swagger_blueprint

app = Sanic()
app.blueprint(swagger_blueprint)

class Car:
    make: str
    model: str
    year: int

@app.get("/car/<id:int>")
@doc.summary("Gets a car")
@doc.produces(Car)
async def get_car(request, car_id):
    return json({
                 "make": "Nissan",
                 "model": "370Z",
    })

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000)
```

### CODE REVIEW

**Comment by viniciusd** [comment]
I acknowledge there aren't tests related to this kind of feature. In a future PR, I can work on adding tests to the object serialization.

**Comment by chenjr0719** [comment]
@viniciusd Sorry for the delay. About the conflict, please solve it. Maybe you can put the example at [here](https://github.com/huge-success/sanic-openapi/blob/master/docs/sanic_openapi/fields.md#object). And, I think it is better to add test in this PR or the code coverage might decrease after merge this PR.

**Comment by viniciusd** [comment]
Thanks for the feedback!
Conflict is now solved 👍 

Gonna add the example to the docs

**Comment by viniciusd** [comment]
Sorry for the delay, got pushed back by a few other tasks.

Added docs to the `fields.md` file :)

**Pull request merged**
