### PR TITLE
doc.py add operation

### PR DESCRIPTION
**Pull request by pytomtoto**
fix swagger page

### CODE REVIEW

**Comment by chenjr0719** [comment]
@ahopkins I think this PR can be merged.

**Comment by ahopkins** [comment]
@pytomtoto Looks like there is some tests that keep failing CI. Can you please look into correcting them?

**Comment by pytomtoto** [comment]
> @pytomtoto Looks like there is some tests that keep failing CI. Can you please look into correcting them?

done.

**Comment by pytomtoto** [comment]
> Hi, @pytomtoto
> 
> Would you please add some test for your contribution?
> Here is a similar test:
> https://github.com/huge-success/sanic-openapi/blob/c79a0b34535d2039d6901d166c39583017f67d17/tests/test_decorators.py#L37-L49

done @chenjr0719

**Pull request merged**
